### ISSUE TITLE
Test DFA class usage in Automata GUI

### ISSUE THREAD

**Issue by kvrigor** [kvrigor/dfa2cfg#2]
Check [ConsolApp.vb](https://github.com/kvrigor/dfa2cfg/blob/master/DFA2CFG/Codecs/Test/ConsoleApp.vb) for sample usage

To better isolate different features of our software, how about adding a reference to Codecs.dll instead of including its project source code to your solution? With this you'll need to build the binaries first from Codecs.vbproj.

**Comment by chesterlbtan** [comment]
![image](https://user-images.githubusercontent.com/22214030/27085958-569cc940-5083-11e7-9c13-ada5a0ae1e92.png)
