### ISSUE TITLE
Print DFA transition table in a nice tabular format

### ISSUE THREAD

**Issue by kvrigor** [kvrigor/dfa2cfg#4]
Provide code to the method below found on [DFA.vb](https://github.com/kvrigor/dfa2cfg/blob/master/DFA2CFG/Codecs/Codecs/DFA.vb#L274):

```
Protected Function PrintTransitionTable() As String
            'TODO: Display transition functions in tabular format 
            Return ""
End Function
```

Will be useful in pretty-printing the DFA 5-tuple definition!

**Comment by chesterlbtan** [comment]
![image](https://user-images.githubusercontent.com/22214030/27085939-49cc8336-5083-11e7-8310-72392b2fa352.png)
